@JWT_Bearer_Token_HostAddress = https://localhost:7105
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhd2EiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MjEwNDE0MDksImV4cCI6MTcyMTA1MjIwOSwiaWF0IjoxNzIxMDQxNDA5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDU0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo0MjAwIn0.Gwn4ifJLR0kAaxPDOL9Ldth9vvfluX1qKk7wftK5APw

###


GET {{JWT_Bearer_Token_HostAddress}}/freeAccess

###



GET {{JWT_Bearer_Token_HostAddress}}/userOrAdminAccess
Authorization: Bearer {{authToken}}

###



GET {{JWT_Bearer_Token_HostAddress}}/adminAccess
Authorization: Bearer {{authToken}}

###
